### ISSUE TITLE
error installing angular-firebase

### ISSUE THREAD

**Issue by st-clair-clarke** [hejazy/angular-firebase#1]
Hi,
I am using @angular/*: "^6.1.9" and attempting to install

`yarn add angular-firebase`

However, I am getting the following warning with failure to install

```
warning "angular-firebase > firebase > @firebase/database@0.2.2" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/auth > @firebase/auth-types@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/functions@0.1.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/messaging@0.2.4" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/storage@0.1.9" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/firestore@0.4.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/database > @firebase/database-types@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/storage > @firebase/storage-types@0.1.3" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/firestore > @firebase/firestore-types@0.3.0" has unmet peer dependency "@firebase/app-types@0.x".
warning "angular-firebase > firebase > @firebase/functions > @firebase/messaging-types@0.1.3" has unmet peer dependency "@firebase/app-types@0.x".
error An unexpected error occurred: "EPERM: operation not permitted, unlink 'J:\\workspace\\ngnx\\node_modules\\node-sass\\vendor\\win32-x64-64\\binding.node'".

```

The only error in the console is 

`error An unexpected error occurred: "EPERM: operation not permitted, unlink 'J:\\workspace\\ngnx\\node_modules\\node-sass\\vendor\\win32-x64-64\\binding.node'".`

Sorry I don't have any more explicit info.

What do you think is the problem?

Cheers

**Comment by hejazy** [comment]
Hi, 
please note that the error of "operation not permitted, unlink 'node_modules\\node-sass\\vendor\\win32-x64-64\\binding.node' " is a common error.
this error occurred because of sass transpiler error not angular-firebase module error,

however to solve this error you just need to rebuild node-sass module in the project directory to build the binding for your current environment.

```console
npm rebuild node-sass 
```

**Comment by hejazy** [comment]
Hi, 
please note that the error of "operation not permitted, unlink 'node_modules\\node-sass\\vendor\\win32-x64-64\\binding.node' " is very common.
this error occurred because of sass transpiler not angular-firebase module,

however to solve this error you just need to rebuild node-sass module in the project directory to build the binding for your current environment.

```console
npm rebuild node-sass 
```

**Comment by st-clair-clarke** [comment]
Followed your instruction with same result.

NB. I have not had this problem with other packages.

**Comment by hejazy** [comment]
Hi , I will push tonight an update that will fix the "rxjs/add/operator/map" error that occure with angular 6.1 versions.

### Note that :
 this update will not solve your problem because the angular-firebase has no relation will any styling code "css, scss, ... etc" or package "@angular/animation, ... etc".

### To fix your problem follow this steps:
- open the .angular-cli.json file in the project folder
- make sure that your main style is scss {"styleExt": "scss"}
- make sure the style files are ending with scss not css
- run this code to make sure that every thing fine.
```console
ng set defaults.styleExt scss
```
- then reinstall node-sass again with
```console
npm install node-sass 
```
- then rebuild it
```console
npm rebuild node-sass 
```

**If the error not solved, do not hesitate to ask.
